export function ReviewTag() {
    return {
        Porn: "涉黄",
        Terrorism: "暴恐",
        Politics: "涉政",
        Ads: "广告",
        Illegal: "违法",
    }
}

export function Category() {
    return {
        ObsceneBehaviour: "色情低俗",
        Sexuality: "严重色情",
        SexProducts: "性用品",
        Sexy: "性感内容",
        PornOCR: "色情文本",
        Moan: "低俗语音",
        PositiveCharacter: "正面人物",
        NegativeFigure: "负面人物",
        ForeignLeaders: "地区领导",
        Underdog: "劣迹艺人",
        Gallery: "违规图库",
        PositiveFlagsLogos: "正面标识",
        NegativeFlagsLogos: "负面标识",
        ChinaMap: "中国地图",
        SpecialItems: "特殊物品",
        PolityOCR: "政治文本",
        NegativeContent: "负面内容",
        PositiveContent: "正面内容",
        SpecialDress: "特殊着装",
        Uniforms: "军警制服",
        Firearms: "枪支武器",
        LargeWeapons: "大型武器",
        ColdWeapons: "冷兵器",
        CrowdGathering: "人群聚集",
        BloodyScenes: "血腥场景",
        FireExplosion: "火灾爆炸",
        TerrorismActs: "暴力恐怖",
        Illegal: "违法违规",
        TerrorOCR: "暴恐文本",
        Weapon: "暴恐相关",
        Abuse: "谩骂",
        QRCode: "二维/条形码",
        LOGO: "LOGO检测",
        AdOCR: "广告文本",
    }
}

export function SubLabel() {
    return {
        ACGPorn: "ACG色情",
        NakedAnimal: "动物裸露",
        PornHigh: "严重色情",
        SexAids: "性用品",
        NakedArt: "裸露艺术",
        WomenSexy: "女性性感",
        MenSexy: "男性性感",
        WomenSexyBack: "女性背部",
        WomenSexyChest: "女性胸部",
        WomenSexyLeg: "女性腿部",
        ACGSexy: "ACG性感",
        SexySimilar: "性感画面",
        HipCloseUp: "臀部性感",
        FootCloseUp: "足部特写",
        SexyBehavior: "性行为",
        WomenPrivatePart: "女性下体",
        WomenChest: "女性胸部",
        MenPrivatePart: "男性下体",
        ButtocksExposed: "臀部",
        NakedChild: "儿童裸露",
        PornSimilar: "色情画面",
        AppLogo: "应用LOGO",
        MovieLogo: "电影LOGO",
        CCTVLogo: "央视LOGO",
        LocalTVLogo: "地方Logo",
        QRCODE: "二维码",
        Blood: "血腥画面",
        Knife: "冷兵器",
        Crowd: "人群聚集",
        Gun: "热武器",
        Fire: "火灾爆炸",
        BigWeapon: "军事武器",
        Burka: "特殊服饰",
        Terrorism: "暴力犯罪",
        ACGTerror: "ACG暴恐",
        TerrorSimilar: "暴恐画面",
        Uniform: "军警制服",
    }
}